{
 "title": "Average Temperature",
 "time": { "from": "2025-09-26T21:05:00.000Z", "to": "2025-09-26T21:07:02.063Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Predicted Failures (Next 5 mins)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"failure_predictions\")\r\n  |> filter(fn: (r) => r._field == \"predicted_temp\")  // <-- ADD THIS LINE\r\n  |> last()\r\n  |> group(columns:[\"device_id\"])"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_metrics\")\r\n  |> filter(fn: (r) => r.metric_type == \"Temperature\")\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty:false)"
    }
   ]
  },
  {
   "title": "CRITICAL ALERTS - LIVE",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_metrics\")\r\n  |> filter(fn: (r) => r.status == \"Critical\")\r\n  |> last()\r\n  |> group(columns: [\"device_id\"])\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n"
    }
   ]
  },
  {
   "title": "Devices in Critical State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"sensor_metrics\")\r\n  |> filter(fn: (r) => r.status == \"Critical\")\r\n  |> group()\r\n  |> distinct(column: \"device_id\")\r\n  |> count()\r\n"
    }
   ]
  }
 ]
}